  traefik:
    container_name: traefik
    image: traefik:v2.2
    restart: unless-stopped
    user: "0"
    command:
#      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=<YOUR_EMAIL>"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json"
    ports:
      - "80:80"
      - "443:443" 
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/traefik/config:/etc/traefik
    extra_hosts:
      - host.docker.internal:172.17.0.1